name: agriunion
description: Agriunion is an application which manages the Agriculture marketing.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.1
  mockito: ^5.3.2
  http: ^0.13.5
  smooth_page_indicator: ^1.0.0+2
  modal_bottom_sheet: ^2.0.1
  flutter_easyloading: ^3.0.5
  url_launcher: ^6.1.2
  story_view: ^0.13.2
  animated_bottom_navigation_bar: ^0.3.3
  hijri: ^3.0.0
  lottie: ^1.3.0
  shared_preferences: ^2.0.15
  flutter_bloc: ^8.0.0
  equatable: ^2.0.3
  flutter_spinkit: ^5.0.0
  flutter_svg: any
  file_picker: any
  flutter_datetime_picker:
    git:
      url: https://github.com/AlexHartford/flutter_datetime_picker.git
      ref: master
  flutter_native_splash: any
  page_transition: ^2.0.5
  internet_connection_checker: ^0.0.1+4
  badges: ^2.0.2
  get_it: ^7.2.0
  intl: ^0.17.0
  qr_flutter: ^4.0.0
  qr_code_scanner: ^1.0.1
  rxdart: ^0.27.4
  dotted_border: ^2.0.0+2
  simple_animations: ^4.2.0
  dropdown_search: ^5.0.3
  provider: ^6.0.3
  path_provider: ^2.0.11
  pull_to_refresh: ^2.0.0
  dio: ^4.0.6
  flutter_dotenv: ^5.0.2
  flutter_colorpicker: ^1.0.3
  modal_progress_hud_nsn: ^0.3.0
  im_stepper: ^1.0.1+1
  flutter_speed_dial: ^6.2.0
  flutter_stories: ^0.3.1
  font_awesome_flutter: ^10.3.0
  flutter_local_notifications: ^13.0.0
  firebase_messaging: ^14.2.1
  firebase_core: ^2.4.1
  open_filex: ^4.3.2
  video_player: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  flutter_launcher_icons: "^0.9.2"
  flutter_lints: ^1.0.0
  change_app_package_name: ^1.1.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - .env
    - .env.test
    - assets/images/
    - assets/langs/
    - assets/icons/
    - assets/animation/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf

flutter_native_splash:
  color: "#42a5f5"
  #background_image: "assets/background.png"
  image: assets/splash.png

  android_12:
    image: assets/splash.png

    # Splash screen background color.
    color: "#FFFFFF"
  android: true
  ios: true
  #web: false

  android_gravity: center
